### ISSUE TITLE
Incorrect tag names?

### ISSUE THREAD

**Issue by physikerwelt** [wooorm/mathml-tag-names#6]
I guess the following names were added by mistake:
https://github.com/wooorm/mathml-tag-names/blob/ba884b49f828057fabb026bd6b6cdeba3e886bc1/index.json#L94-L95

https://github.com/wooorm/mathml-tag-names/blob/ba884b49f828057fabb026bd6b6cdeba3e886bc1/index.json#L114

**Comment by wooorm** [comment]
`m:apply` and `m:mrow` are listen in [mathml 2](https://www.w3.org/TR/MathML2/appendixl.html#index.elem).

`<mi">` is [listed](https://www.w3.org/TR/MathML3/chapter6.html#interf.nonxml) in mathml 3, but as it’s the only mention, it seems like a typo. What do you think?

**Comment by wooorm** [comment]
Seems m:apply and m:mrow [are also examples](https://www.w3.org/TR/MathML2/appendixa.html#parsing.dtd.prefix).

**Comment by physikerwelt** [comment]
I guess all of the examples aren't XML tag names, that can be used by a JavaScript program. The namespace prefix  `m` is (as far as I can tell) just an example for a human reader. It could also be any other namespace prefix, e.g., `math` or `n`.

@davidcarlisle Can you fix the typo in the [editors draft](https://github.com/w3c/mathml/tree/gh-pages)?

**Comment by wooorm** [comment]
> I guess all of the examples aren't XML tag names, that can be used by a JavaScript program. The namespace prefix m is (as far as I can tell) just an example for a human reader. It could also be any other namespace prefix, e.g., math or n.

Yup! So I’ll remove these three cases. Anything else you found? P.S. thanks for checking! 👍

**Comment by davidcarlisle** [comment]
@physikerwelt  you mean the `<mi"` ? That seems to have been fixed some time ago (I think it was an artifact of the diff markup)  I don't see it in the current sources or in the generated html

https://w3c.github.io/mathml/chapter6.html#interf.nonxml

**Comment by wooorm** [comment]
@davidcarlisle I was crawling <https://www.w3.org/TR/MathML3/appendixi.html>, which included it!

@physikerwelt I removed the two examples from MathML 2

Thanks both!

**Comment by davidcarlisle** [comment]
On 1 May 2018 at 08:25, Titus <notifications@github.com> wrote:

> @davidcarlisle <https://github.com/davidcarlisle> I was crawling
> https://www.w3.org/TR/MathML3/appendixi.html, which included it!
>

yes sorry the status is "tricky" the github draft is an "official" w3c
editors draft under the w3c organisation at github, and If you do spot
anything we can fix it there, but getting any changes pushed back to the
W3C site  requires getting together enough changes that need to be
standardised that we can get a new charter for the math Group to restart a
REC trac draft.

**Comment by physikerwelt** [comment]
@davidcarlisle I think 
https://github.com/wooorm/mathml-tag-names/commit/c920c8c9e33510ae9920f85ef5cdf9c5d794234e#diff-efd59cd1bdc5c9ac6d0eaa368f1e149fR27 is the best available solution. I wonder if it really requires a charter for editorial changes?
