### ISSUE TITLE
Add list of self-closing tag names

### ISSUE THREAD

**Issue by stevenvachon** [wooorm/mathml-tag-names#7]
Like was done with `voidHtmlTags` in [html-tags](https://npmjs.com/html-tags).

**Comment by wooorm** [comment]
Hi Steve!

There are no void MathML (or SVG) tags. [Void is a concept in HTML](https://html.spec.whatwg.org/multipage/syntax.html#void-elements), which some elements have: they can never contain anything. The “self-closing” `/` in opening tags (`<div/>`) or closing tags (`</div/>`) is always ignored.

All MathML and SVG elements can be marked as self-closing by adding that slash: `<rect/>` opens and immediately closes that element.

Therefore, unless I’m missing something (?), a list of “self-closing” of these would be identical to the list of tag names itself!

**Comment by stevenvachon** [comment]
I know what void elements are. MathML does have "*known* self-closing" tags, however; which are tags that are expected to never contain children. `<mspace>` is one such example.

**Comment by wooorm** [comment]
I searched both the MathML and SVG specs for “self-closing”, and couldn’t find anything? What is your source?

**Comment by stevenvachon** [comment]
A "known self-closing tag" is a term I use when referring to an element that is expected to never contain children.

**Comment by stevenvachon** [comment]
From [section 3.2.7.1](https://www.w3.org/TR/MathML3/chapter3.html#presm.mspace) of the spec:
> An mspace empty element

**Comment by wooorm** [comment]
Interesting, when searching for that term in MathML, I find the elements: `none, mspace, mprescripts`.

It’s a slightly different use case than [`html-void-elements`](https://github.com/wooorm/html-void-elements), so I don’t feel a need maintaining it, but I think it makes sense that such a package exists, want to create it?

**Comment by stevenvachon** [comment]
As I've said above, I think it's best to follow what [html-tags](https://npmjs.com/html-tags) has done, as it reduces the number of dependencies in a project.

**Comment by wooorm** [comment]
Thats a different case and I also don’t believe that metric is useful.
You’ve made your point before, I made my stance clear. I find this a bit annoying. I’m locking this.
